const HASH='6e41008ffe6421500c02225a866abcc5c53099a899a6c25fb31f06a99f9d6207';
const CORR={
'seance-1.html':[
['Exercice 1','374 est une valeur numérique issue du convertisseur, pas une température.','Le capteur produit une tension, puis le convertisseur code cette tension sur une plage numérique.','Confondre mesure physique, signal et donnée numérique.','À quelle étape la grandeur « °C » disparaît-elle ?'],
['Exercice 2','Avec la convention donnée 0–3,3 V ↔ 0–1023, un pas vaut environ 3,23 mV.','La résolution dépend de la plage de tension et du nombre de niveaux disponibles.','Ne pas confondre résolution et précision. Pour un convertisseur 10 bits idéal, on rencontre aussi Vref/1024 ≈ 3,22 mV par LSB selon la convention utilisée.','Deux tensions proches peuvent-elles donner le même code ?'],
['Exercice 3','Oui, plusieurs températures proches peuvent produire la même valeur numérique.','La quantification regroupe une plage continue de valeurs physiques dans un niveau discret.','Un affichage avec beaucoup de chiffres ne garantit pas une meilleure mesure.','Que perd-on quand on passe du continu au discret ?'],
['Exercice 4','374 correspond à environ 1,206 V : 374/1023 × 3,3. La loi du capteur est linéaire de 0,50 V à 2,50 V pour 0 à 100 °C, soit 0,02 V/°C. On obtient donc environ (1,206 − 0,50)/0,02 = 35,3 °C.','On reconstruit successivement la tension puis la grandeur physique à partir du modèle du capteur.','Le résultat est une estimation : quantification, tolérance du capteur et étalonnage limitent la précision.','Pouvez-vous écrire la chaîne complète : température → tension → code puis code → tension → température ?'] ],
'seance-2.html':[
['Exercice 1','Le programme n’est pas faux : il applique correctement une règle trop sensible aux fluctuations autour de 28 °C.','Le problème vient du couplage entre bruit de mesure et seuil unique.','Ne pas chercher d’abord une erreur de syntaxe.','Que se passe-t-il si la mesure oscille de part et d’autre du seuil ?'],
['Exercice 2','Une hystérésis consiste à utiliser deux seuils, par exemple ON au-dessus de 28 °C et OFF en dessous de 26 °C.','Le système conserve son état entre les deux seuils et évite les commutations rapides.','Ce n’est pas la seule solution possible : filtrage, temporisation, moyenne glissante existent aussi.','Pourquoi deux seuils stabilisent-ils la décision ?'],
['Exercice 3','Une moyenne glissante réduit les fluctuations rapides mais introduit un retard.','Filtrer améliore la stabilité au prix d’une réponse moins instantanée.','Un filtre ne corrige pas forcément un capteur mal calibré.','Quel compromis faites-vous entre stabilité et réactivité ?'],
['Exercice 4','Le choix dépend du besoin : sécurité, confort, vitesse de réaction, coût énergétique.','Une décision technique est liée au cahier des charges, pas à une recette universelle.','Éviter « le meilleur algorithme » sans critère.','Quelle exigence du système doit guider votre choix ?'] ],
'seance-3.html':[
['Exercice 1','Le système obtient 9 900 bonnes réponses sur 10 000, soit 99 %. Pourtant ce score ne permet pas de conclure qu’il est bon.','Il faut connaître la répartition des classes et surtout le type d’erreurs commises.','L’accuracy seule peut être trompeuse sur des données déséquilibrées.','Combien y a-t-il de vrais cas positifs dans l’échantillon ?'],
['Exercice 2','Le modèle ne détecte aucun incendie : il produit 100 faux négatifs sur 100 incendies.','Il fait donc 100 % de faux négatifs sur les cas critiques malgré 99 % de réussite globale.','Une excellente moyenne peut masquer un échec majeur.','Quelle erreur coûte le plus cher ici ?'],
['Exercice 3','Il faut distinguer au minimum vrais positifs, faux positifs, vrais négatifs et faux négatifs.','La matrice de confusion montre quelles erreurs le modèle commet.','Ne pas transformer la séance de 3e en cours statistique avancé : l’objectif est le raisonnement critique.','Quelle case de la matrice devez-vous surveiller en priorité ?'],
['Exercice 4','Il faut séparer données d’entraînement et données de test.','Tester sur les mêmes données que celles utilisées pour apprendre surestime la performance réelle.','Un score élevé n’est pas une preuve de généralisation.','Le modèle réussit-il sur des exemples qu’il n’a jamais vus ?'] ],
'seance-4.html':[
['Exercice 1','La décision finale dépend de la logique définie par les concepteurs et des données disponibles ; le capteur ne « décide » pas à lui seul.','Le capteur fournit une information d’entrée, l’algorithme applique une règle ou un modèle.','Éviter d’anthropomorphiser le système.','Qui a choisi les règles et les données prises en compte ?'],
['Exercice 2','Une expression possible : OUVRIR = Présence ET Badge_valide ET NON Alarme ET (Horaire_autorisé OU Mode_urgence).','L’écriture logique rend les conditions explicites et testables.','Attention à la priorité des opérateurs et aux cas non prévus. D’autres règles seraient possibles selon le cahier des charges.','Quels cas limites devez-vous tester ?'],
['Exercice 3','Avec la règle proposée : Cas A = fermé, car Horaire=faux et Urgence=faux. Cas B = fermé, car Présence=faux et Alarme=vrai. Si, dans le cas A, Urgence devient vrai, la porte s’ouvre puisque toutes les autres conditions sont alors satisfaites.','Modifier une seule entrée permet de tester la sensibilité de la décision et de vérifier le modèle logique.','Le résultat dépend de la règle choisie : il faut toujours expliciter le cahier des charges avant de juger la sortie.','Quelle condition suffit à faire basculer le cas A ?'],
['Exercice 4','Pour vérifier la compréhension, demandez de prédire un cas nouveau, justifier la sortie et modifier une condition.','Le transfert et l’auto-explication sont plus informatifs qu’une simple exécution réussie.','Réussite immédiate ≠ apprentissage durable.','Que se passe-t-il si une seule entrée change ?'] ]};
const MIRROR={
'seance-1.html':'Focale cognitive : conceptions initiales et modèle mental. Faites distinguer explicitement grandeur physique, signal, donnée et information avant la formalisation.',
'seance-2.html':'Focale cognitive : difficulté productive et charge cognitive. L’obstacle utile est le seuil instable ; évitez d’ajouter simultanément un logiciel inconnu ou trop de paramètres.',
'seance-3.html':'Focale cognitive : biais d’intuition et confiance excessive dans un score. Faites prédire avant de révéler la répartition des classes.',
'seance-4.html':'Focale cognitive : auto-explication, transfert et métacognition. Faites justifier la décision puis modifier un paramètre pour tester la solidité du modèle mental.'};
async function hash(s){const d=new TextEncoder().encode(s);const h=await crypto.subtle.digest('SHA-256',d);return [...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderCorrection(){const root=document.getElementById('correction-root');if(!root)return;const key=location.pathname.split('/').pop();const rows=CORR[key]||[];root.innerHTML=`<section class="section"><div class="card"><span class="kicker">Correction de la séance</span><h2>Comparez votre raisonnement</h2><p>La correction est volontairement détaillée : réponse attendue, justification, point de vigilance et relance possible.</p><div class="lock"><div class="lock-row"><input id="corr-pass" type="password" placeholder="Mot de passe de correction" autocomplete="off"><button id="corr-btn" type="button">Déverrouiller</button></div><div id="corr-status"></div></div><div id="corr-content" class="corr-content">${rows.map(r=>`<div class="corr-item"><h3>${esc(r[0])}</h3><p><strong>Réponse attendue.</strong> ${esc(r[1])}</p><p><strong>Pourquoi ?</strong> ${esc(r[2])}</p><div class="watch"><strong>Point de vigilance.</strong> ${esc(r[3])}</div><div class="relance"><strong>Relance possible.</strong> ${esc(r[4])}</div></div>`).join('')}<div class="corr-item"><h3>Retour sur votre scénarisation</h3><p>${esc(MIRROR[key]||'')}</p></div></div></div></section>`;document.getElementById('corr-btn').onclick=unlock;document.getElementById('corr-pass').addEventListener('keydown',e=>{if(e.key==='Enter')unlock()});if(sessionStorage.getItem('corr_donnees_2027')==='1')document.getElementById('corr-content').classList.add('open')}
async function unlock(){const p=document.getElementById('corr-pass').value;const ok=(await hash(p.trim()))===HASH;document.getElementById('corr-status').textContent=ok?'Correction déverrouillée.':'Mot de passe incorrect.';if(ok){sessionStorage.setItem('corr_donnees_2027','1');document.getElementById('corr-content').classList.add('open')}}
document.addEventListener('DOMContentLoaded',renderCorrection);